#!/usr/bin/env python3
"""Generate a static run-id navigation index from registry and logs."""
from __future__ import annotations
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/appendices/run_id_index.md'
SOURCES = [ROOT / 'docs/report/experiment-registry.html', ROOT / 'docs/experiment-log.md', ROOT / 'docs/experiment-lines.md']
# Broad enough to retain historical IDs; only known experiment-family prefixes are accepted.
PATTERN = re.compile(r'(?<![A-Za-z0-9])((?:nglab|optv5|causalv5|s1v5|blrabs|ffqv5|mixv5|ls20ep|smoke|t[1-9]|l[1-6])[_A-Za-z0-9.-]{2,})(?![A-Za-z0-9])')
def main():
    found = {}
    for source in SOURCES:
        text = source.read_text(errors='ignore')
        for run_id in PATTERN.findall(text):
            run_id = run_id.rstrip('.,:;')
            # The source documents also contain glob patterns, family labels,
            # and asset names (e.g. `l1_forking.png`).  They are navigation
            # noise, not run IDs.  Keep only identifier-like tokens.
            if (len(run_id) < 5 or run_id.endswith('_') or '.' in run_id
                    or '*' in run_id or '{' in run_id or '}' in run_id
                    or run_id.endswith(('png', 'svg', 'py', 'html'))):
                continue
            found.setdefault(run_id, set()).add(source.relative_to(ROOT).as_posix())
    rows = sorted(found.items())
    lines = ['# Appendix H.1.3 - Run ID index', '', '> Generated by `docs/tools/gen_run_id_index.py`. This is navigation; `_fixed/summary.json` and the experiment log remain authoritative.', '', f'Generated entries: **{len(rows)}**. IDs without `_fixed` are retained for historical/provenance traceability.', '', '| run_id | family | fixed marker | source documents |', '|---|---|---|---|']
    for run_id, sources in rows:
        marker = 'yes' if run_id.endswith('_fixed') else 'no / inspect'
        family = run_id.split('_', 1)[0]
        lines.append(f"| `{run_id}` | `{family}` | {marker} | {', '.join('`'+s+'`' for s in sorted(sources))} |")
    lines += ['', '## Interpretation', '', '- An entry does not prove completion or local presence.', '- Completion requires a matching `_fixed` directory, `summary.json`, registration section, and step/seed/setting evidence.', '- Remote-only and historical IDs remain discoverable but must retain that label in prose.']
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'wrote {OUT} ({len(rows)} run IDs)')
if __name__ == '__main__': main()
